version: 2.1
jobs:
  deploy:
    working_directory: ~/app
    docker:
      - image: makki0205/deploy
    steps:
      - checkout
      - run:
          name: aws login
          command: make aws/credentials
      - run:
          name: deploy
          command: make aws/deploy

workflows:
  test_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
